name: Publish

on:
  push:
    branches: [main]
  pull_request:

env:
  DEBUG: 'napi:*'
  MACOSX_DEPLOYMENT_TARGET: '10.13'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-pc-windows-msvc
          - x86_64-unknown-linux-gnu
          - aarch64-unknown-linux-gnu
          - x86_64-apple-darwin
          - aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      - uses: Swatinem/rust-cache@v2

      - name: Install ziglang
        uses: goto-bus-stop/setup-zig@v1
        with:
          version: 0.10.0

      - run: cargo install cargo-xwin
        if: matrix.target == 'x86_64-pc-windows-msvc'

      - name: Check formatting
        run: cargo fmt --all --check

      - name: Node install
        run: npm i

      - name: Build Mac and Linux
        if: matrix.target != 'x86_64-pc-windows-msvc'
        run: npm run build -- --zig --target ${{ matrix.target }}

      - name: Build Windows
        if: matrix.target == 'x86_64-pc-windows-msvc'
        run: npm run build -- --target ${{ matrix.target }}

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OS specific binaries
          path: dist
          if-no-files-found: error

  deploy:
    # prevents this action from running on forks or pull requests
    if: ${{ github.repository == 'ceifa/tiktoken-node' && github.event_name == 'push' }}

    runs-on: ubuntu-20.04
    needs: build

    steps:
      - uses: actions/checkout@v3

      - name: Download build
        uses: actions/download-artifact@v3
        with:
          name: OS specific binaries
          path: dist/

      - name: Log files
        run: |
          echo "- Root directory:" && ls
          echo "- Dist directory:" && ls -R dist

      - name: Publish to npm
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
